/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.10.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as engine from "../engine.js";
import type * as games from "../games.js";
import type * as lib_openai from "../lib/openai.js";
import type * as search from "../search.js";
import type * as testing_clearAll from "../testing/clearAll.js";
import type * as testing_wrappers from "../testing/wrappers.js";
import type * as users from "../users.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  engine: typeof engine;
  games: typeof games;
  "lib/openai": typeof lib_openai;
  search: typeof search;
  "testing/clearAll": typeof testing_clearAll;
  "testing/wrappers": typeof testing_wrappers;
  users: typeof users;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
